package bmo5.bmo5tests.suites;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import bmo5.bmo5tests.tests.bmo.*;

@RunWith(Suite.class)
@SuiteClasses({
	Test_003_SearchPage.class,
	Test_003_Search_SaveSearch.class,
	Test_004_1_AdvancedSearch.class,
	Test_004_2_AdvancedSearchListingPage.class,
	Test_004_3_AdvancedSearchManage_Clipboard.class,
	Test_004_4_AdvancedSearchSavedSearches.class,
	Test_005_01_WebinarsAndPodcasts_Phase2.class,
	Test_005_Header_Help.class,
	Test_006_Header_ServiceUpdates.class,
	Test_007_Header_Methodology.class,
	Test_009_1_CreateNewCustomAlert.class,
	Test_009_2_EditCustomAlert.class,
	Test_009_3_StopCustomAlert.class,
	Test_009_4_DeleteCustomAlert.class,
	Test_009_10_SectorAlerts.class,
	Test_009_11_FinancialMarketsAlerts.class,
	Test_009_6_Create_NewPdfAlert.class,
	Test_009_7_EditPdf_Alert.class,
	Test_009_8_StopPdf_Alert.class,
	Test_009_5_Delete_Pdf_Alert.class,
	Test_009_9_DailyMacroAlerts.class,
	Test_009_Alerts_Create_NewCustom_NewReport_Alert_SaveWithoutTitle.class,
	Test_010_1_SavedContent_SavedArticles.class,
	Test_010_2_SavedContent_SavedReports.class,
	Test_010_3_SavedContent_SavedViews.class,
	Test_010_4_SavedContent_SavedSearches.class,
	Test_010_5_SavedContent_SavedMNC.class,
	Test_010_6_SavedContent_SavedData.class,
	
	Test_010_Login.class,
	Test_010_RetrievePassword.class,
	Test_011_NavigationBar_ServiceDropdown.class,
	Test_011_ThreePillarNavigationTabs.class,
	Test_011_1_StategicAnalysisAndReportsStategicAnalysis_Phase2.class,
	Test_011_2_StrategicAnalysisAndReportsStrategicAnalysisPreviewArticle_Phase2.class,
	Test_011_3_StrategicAnalysisAndReportsStategicAnalysisArticlePage_Phase2.class,
	Test_012_NavigationBar_CountryRisk.class,
	Test_013_NavigationBar_FinancialMarkets.class,
	Test_013_1_StrategicAnalysisAndReports_Reports_Phase2.class,
	Test_013_2_StrategicAnalysisAndReports_Reports_PreviewReport_Phase2.class,
	Test_013_3_StrategicAnalysisAndReports_Reports_ReportPage_Phase2.class,
	Test_014_NavigationBar_Geography.class,
	Test_PaginationPersistence.class,
	Test_015_2_HotTopicsSingleArticle.class,
	Test_015_3_HotTopicsListingPage.class,
	Test_015_4_HotTopicsPreview.class,
	Test_016_NavigationBar_SpecialReports.class,
	Test_018_2_DailyViews_SingleArticle.class,
	Test_018_4_DailyViews_ListingPage.class,
	Test_018_6_DailyViews_PreviewWindow.class,
	Test_019_2_Analysis_SingleArticle.class,
	Test_019_4_Analysis_ListingPage.class,
	Test_019_6_Analysis_PreviewWindow.class,
	Test_020_02_News_SingleArticle.class,
	Test_020_04_News_ListingPage.class,
	Test_020_06_News_WindowPage.class,
	Test_021_1_ReportsAndStrategicContent_ListingPage.class,
	Test_021_2_ReportsAndStrategicContent_PreviewArticle.class,
	Test_021_3_ReportsAndStrategicContent_ArticlePage.class,
	Test_022_4_StrategicAnalysis_GeoPivot.class,
	Test_022_Header.class,
	Test_023_5_Reports_GeographyPivotPoint.class,
	Test_023_6_Reports_ServicePivotPoint.class,
	Test_023_UserAccount_Account.class,
	Test_024_1_ReportsArchiveListingPage.class,
	Test_024_2_ReportsArchiveLandingPage.class,
	Test_024_2_ReportsArchiveLandingPage_Preview.class,
	Test_025_1_DataAndForecastingPage_UserHasEntitlementsForCountryRisk.class,
	Test_025_3_DataAndForecastingPage.class,
	Test_027_Ratings_CountryRisk.class,
	Test_027_Ratings_SecurityRating_ProjectFinance.class,
	Test_027_Ratings_RiskRewardRatings.class,
	Test_27_Ratings_OperationalRisk.class,
	Test_029_Homepage.class,
	Test_030_Carousel.class,
	Test_034_Footer_TermsAndConditions.class,
	Test_035_Footer_TrackRecord.class,
	Test_036_Footer_ContactUs.class,
	Test_037_Footer_Careers.class,
	Test_047_NewsSubtab.class,
	Test_048_3_BmoEvents.class,
	Test_051_1_Mnc_Home_Page.class,
	Test_051_2_MncSearch.class,
	Test_051_3_Mnc_SelectedCompany_Profile.class,
	Test_051_4_MncExport.class,
	Test_052_1_PdfUser_Landing_Page.class,
	Test_052_2_PdfUser_Listing_Page.class,
	Test_053_1_Mdg001HomePage.class,
	Test_053_2_Mdg003BuildingSelection.class,
	Test_053_3_MdgSelectedCompanyProfile.class,
	Test_053_4_MdgExport.class,
	Test_055_CompanyIntelligence.class,
	
	Test_057_1_DataTool_Download_Xls.class,
	Test_057_2_DataTool_DisplayData.class,
	Test_057_3_Chart.class,
	Test_057_4_Table.class,
	Test_057_5_DataTool_SaveButton.class,
	Test_057_6_Select_Button.class,
	Test_057_7_Chart_Print.class,
	Test_057_8_Chart_Export.class,
	Test_057_9_Chart_New_Text_Annotation.class,
	Test_057_10_Chart_Edit_Text_Annotation.class,
	Test_057_11_Chart_Delete_Text_Annotation.class,
	Test_057_12_Chart_New_Line_Annotation.class,
	Test_057_13_Chart_Edit_Line_Annotation.class,
	Test_057_15_Chart_Format.class,
	Test_057_16_Table_Add_New_Cell_Annotation.class,
	Test_057_17_Table_Edit_Cell_Annotation.class,
	Test_057_18_Table_Delete_Cell_And_Row_Annotations.class,
	Test_057_19_Table_Add_New_Row_Annotation.class,
	Test_057_20_Table_Edit_Row_Annotation.class,
	Test_057_21_Data_Tool_Download_Queue.class,
})
public class SuiteNodeOne {

}
